create database if not exists dapper_db;

create table if not exists t_user
(
    id         bigint generated by default as identity
        constraint t_user_pk
            primary key,
    first_name varchar(50),
    last_name  varchar(50),
    age        integer
);